config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/show'

  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"

  get 'ocupacaos/index'
  get "/" => "auth0#login"

  get 'estados' => 'estados#index'
  post 'estados' =>'estados#create'
  post 'groups/cadastrar'

  get 'auth/authenticate'
  get 'sessions/new'
  get 'users/new'

  post 'users/permissions' => 'users#getPermissions'
  post 'login'   => 'users#auntentication'

  resources :tipo_assembleia
  resources :forma_transicaos
  resources :arquivos
  resources :ocupacaos
  resources :assembleia
  resources :forma_ingressos
  resources :pessoas
  resources :igrejas
  resources :configuracaos
  resources :tipo_documentos
  resources :tipo_enderecos
  resources :documentos
  resources :grau_instrucaos
  resources :groups
  resources :profissaos
  resources :situacaos
  resources :users
  resources :acos
  resources :actions
  resources :cidades
  resources :bairros
  resources :membros
  resources :ministerios

  get 'membros/page/:page' => 'membros#index'
  post 'membros/filter' => 'membros#filter'

  post 'congregacao/:id_igreja' => 'igrejas#create_congregacao'
  put 'congregacao/:id_congregacao' => 'igrejas#update_congregacao'

end

app/models/situacao.rb
class Situacao < ActiveRecord::Base
	has_many 	:membros
	belongs_to	:cliente
	
  	validates_presence_of :descricao, message: "O Campo descrição é obrigatório "
  	validates :descricao, uniqueness: { scope: [:descricao, :cliente_id], message: "Situação já foi cadastrado" }
end

app/controllers/situacaos_controller.rb
class SituacaosController < ApplicationController
  before_action :set_situacao, only: [:show, :edit, :update, :destroy]

  # GET /situacaos
  # GET /situacaos.json
  def index
    @situacaos = Situacao.where cliente_id: session[:ClientId]
  end

  # GET /situacaos/1
  # GET /situacaos/1.json
  def show
  end

  # GET /situacaos/new
  def new
    @situacao = Situacao.new
  end

  # GET /situacaos/1/edit
  def edit
  end

  # POST /situacaos
  # POST /situacaos.json
  def create
    msg = "Situação cadastrada com sucesso!"
    status = 201
    situacao_param = params[:situacao]    
    begin
      unless situacao_param[:descricao]
        raise "Descrição invalido!"
      end
      situacao = Situacao.new(situacao_param.to_hash)      
      unless situacao.save
        msg = ""    
        situacao.errors.each do |field, msg_erro|
          unless msg == ""
            msg << ' - ' + msg_erro 
          else
            msg << msg_erro
          end
        end
        raise msg
      end 
      render :json => {data: msg}.to_json, status: status            
    rescue => erro
      render :json =>  {data: erro.message}.to_json , status: :unprocessable_entity     
    end
  end

  # PATCH/PUT /situacaos/1
  # PATCH/PUT /situacaos/1.json
  def update
    respond_to do |format|
      if @situacao.update(situacao_params)
        format.json { render :show, status: :ok, location: @situacao }
      end
    end
  end

  # DELETE /situacaos/1
  # DELETE /situacaos/1.json
  def destroy
    @situacao.destroy
    respond_to do |format|
      format.html { redirect_to situacaos_url, notice: 'Situacao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_situacao
      @situacao = Situacao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def situacao_params
      params.require(:situacao).permit(:descricao)
    end
end

app/views/situacaos/_form.html.erb
<%= form_for(@situacao) do |f| %>
  <% if @situacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@situacao.errors.count, "error") %> prohibited this situacao from being saved:</h2>

      <ul>
      <% @situacao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_field :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/situacaos/edit.html.erb
<h1>Editing Situacao</h1>

<%= render 'form' %>

<%= link_to 'Show', @situacao %> |
<%= link_to 'Back', situacaos_path %>

app/views/situacaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Situacaos</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @situacaos.each do |situacao| %>
      <tr>
        <td><%= situacao.descricao %></td>
        <td><%= link_to 'Show', situacao %></td>
        <td><%= link_to 'Edit', edit_situacao_path(situacao) %></td>
        <td><%= link_to 'Destroy', situacao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Situacao', new_situacao_path %>

app/views/situacaos/new.html.erb
<h1>New Situacao</h1>

<%= render 'form' %>

<%= link_to 'Back', situacaos_path %>

app/views/situacaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @situacao.descricao %>
</p>

<%= link_to 'Edit', edit_situacao_path(@situacao) %> |
<%= link_to 'Back', situacaos_path %>