config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/show'

  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"

  get 'ocupacaos/index'
  get "/" => "auth0#login"

  get 'estados' => 'estados#index'
  post 'estados' =>'estados#create'
  post 'groups/cadastrar'

  get 'auth/authenticate'
  get 'sessions/new'
  get 'users/new'

  post 'users/permissions' => 'users#getPermissions'
  post 'login'   => 'users#auntentication'

  resources :tipo_assembleia
  resources :forma_transicaos
  resources :arquivos
  resources :ocupacaos
  resources :assembleia
  resources :forma_ingressos
  resources :pessoas
  resources :igrejas
  resources :configuracaos
  resources :tipo_documentos
  resources :tipo_enderecos
  resources :documentos
  resources :grau_instrucaos
  resources :groups
  resources :profissaos
  resources :situacaos
  resources :users
  resources :acos
  resources :actions
  resources :cidades
  resources :bairros
  resources :membros
  resources :ministerios

  get 'membros/page/:page' => 'membros#index'
  post 'membros/filter' => 'membros#filter'

  post 'congregacao/:id_igreja' => 'igrejas#create_congregacao'
  put 'congregacao/:id_congregacao' => 'igrejas#update_congregacao'

end

app/models/membro.rb
class Membro < ActiveRecord::Base
  has_many :observacaos, as: :observacaomodel
  has_many :membro_ocupacaos
  has_many :ocupacaos, through: :membro_ocupacaos

  
  has_one :situacao
  has_one :profissao
  belongs_to :forma_transicao
  
  belongs_to :pessoa
end

app/controllers/membros_controller.rb
class MembrosController < ApplicationController
  before_action :set_membro, only: [:show, :edit, :update, :destroy]
                               
  def index       
    @membros = Membro.where(nil)
    filter();
  end

  # Função para retornar membros com parametros de filtro
  # Recebe uma Requisição GET /membros.json?nome=Charley&page=1
  # @author Charley Oliveira <charleycesar@gmail.com>
  # @return [Object] {data=>[membros],paginate=>[opcoes de paginar] } Retorna os membro filtrados pelo parametro passado pela url[page,nome]
  def filter
    @membros = @membros.joins(:pessoa).includes(pessoa:[:telefones,:enderecos,:emails])
    @membros = @membros.where("nome ilike '%"+params[:nome]+"%'") if params[:nome].present?
    @membros = @membros.paginate(:page => params[:page], :per_page =>Isiib::PAGINATION[:limit]) if params[:page].present?
  end

  # GET /membros/1
  # GET /membros/1.json
  def show
  end
         
  # GET /membros/new
  def new
    @membro = Membro.new
  end

  # GET /membros/1/edit
  def edit
  end

  # POST /membros
  # POST /membros.json  
  def create
    msg = {data: "Membro Cadastrado com sucesso!"}.to_json
    status = 201
    membro = Membro.new
    #Salvando Observaçoes
    if params[:membro][:observacoes]
      unless params[:membro][:observacoes].kind_of? Array                
        raise 'Observação invalida'
      end
      params[:membro][:observacoes].each do |observacao|
        observacao_save = Observacao.new observacao.to_hash     
        membro.observacaos << observacao_save
      end    
    end
    
    #Convert to hash
    pessoa = Pessoa.new params[:pessoa].to_hash
    membro.pessoa = pessoa
    
    enderecos = params[:enderecos]
    telefones = params[:telefones]
    emails    = params[:emails]
    
    begin    
      #Obriga ter ao menos um endereco
      unless enderecos.kind_of? Array                
        raise 'Endereço não é um hash'
      end
      enderecos.each do |param_endereco|
        bairro = Bairro.find_by_bairro param_endereco[:bairro]
        #cria um novo bairro
        unless bairro
          bairro = Bairro.new
          bairro.bairro = param_endereco[:bairro]
          bairro.cidade_id = param_endereco[:cidade_id]
          bairro = bairro.save  
        end
        param_endereco.delete(:cidade_id)
        param_endereco.delete(:bairro)
        param_endereco.delete(:estado)
        endereco_save = Endereco.new param_endereco.to_hash
        endereco_save.bairro = bairro
        pessoa.enderecos << endereco_save
      end

      if telefones 

        unless telefones.kind_of? Array
          raise "Telefone não é um hash"
        end
        #Cadastra Telefones
        telefones.each do |telefone|
          #Salvar observação
          observacao = Observacao.new
          observacao.observacao = telefone[:observacao] 
          telefone.delete(:observacao);  
          telefone_save = Telefone.new telefone.to_hash
          telefone_save.observacaos << observacao
          pessoa.telefones << telefone_save
        end

      end

      if emails

        unless emails.kind_of? Array
          raise "Emails não é um hash"
        end
        #Cadastra Emails
        emails.each do |email|
          email_save = Email.new email.to_hash
          pessoa.emails << email_save
        end
      
      end

      unless pessoa.save   
        msg = ""    
        pessoa.errors.each do |field, msg_erro|
            msg << msg_erro + '\n'
        end
      end      
        render :text => msg, status: status      
    rescue => erro
      render :text => erro , status: :unprocessable_entity      
    end
  end

  # PATCH/PUT /membros/1
  # PATCH/PUT /membros/1.json
  def update
    respond_to do |format| 
      if @membro.update(membro_params)
        format.html { redirect_to @membro, notice: 'Membro was successfully updated.' }
        format.json { render :show, status: :ok, location: @membro }
      else
        format.html { render :edit }
        format.json { render json: @membro.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /membros/1
  # DELETE /membros/1.json
  def destroy
    @membro.destroy
    respond_to do |format|
      format.html { redirect_to membros_url, notice: 'Membro was successfully destroyed.' }
      format.json { head :no_content }
    end    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membro      
      @membro = Membro.find(params[:id])      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membro_params

      params.require(:membro).permit(:data_batismo,:observacoes)
      params.require(:pessoa).permit(:cpf,:nome,:data_nascimento,:sexo,:forma_tratamento,:nacionalidade,:naturalidade,:grau_instrucao_id,:situacao_id)
      params.require(:enderecos).permit(:cep,:complemento,:logradouro,:numero,:bairro,:cidade_id,:tipo_endereco_id)
    
    end
end

app/views/membros/_form.html.erb
<%= form_for(@membro) do |f| %>
  <% if @membro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membro.errors.count, "error") %> prohibited this membro from being saved:</h2>

      <ul>
      <% @membro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :forma_tratamento %><br>
    <%= f.text_field :forma_tratamento %>
  </div>
  <div class="field">
    <%= f.label :data_nascimento %><br>
    <%= f.datetime_select :data_nascimento %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br>
    <%= f.text_field :sexo %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br>
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :foto %><br>
    <%= f.text_field :foto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/membros/edit.html.erb
<h1>Editing Membro</h1>

<%= render 'form' %>

<%= link_to 'Show', @membro %> |
<%= link_to 'Back', membros_path %>

app/views/membros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Membros</h1>

<table>
  <thead>  
    <tr>
      <th>Nome</th>
      <th>Forma tratamento</th>
      <th>Data nascimento</th>
      <th>Sexo</th>
      <th>Cpf</th>
      <th>Foto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @membros.each do |membro| %>
      <tr>
        <td><%= membro.nome %></td>
        <td><%= membro.forma_tratamento %></td>
        <td><%= membro.data_nascimento %></td>
        <td><%= membro.sexo %></td>
        <td><%= membro.cpf %></td>
        <td><%= membro.foto %></td>
        <td><%= link_to 'Show', membro %></td>
        <td><%= link_to 'Edit', edit_membro_path(membro) %></td>
        <td><%= link_to 'Destroy', membro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Membro', new_membro_path %>

app/views/membros/new.html.erb
<h1>New Membro</h1>

<%= render 'form' %>

<%= link_to 'Back', membros_path %>

app/views/membros/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Nome:</strong>
  <%= @membro.nome %>
</p>

<p>
  <strong>Forma tratamento:</strong>
  <%= @membro.forma_tratamento %>
</p>

<p>
  <strong>Data nascimento:</strong>
  <%= @membro.data_nascimento %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @membro.sexo %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @membro.cpf %>
</p>

<p>
  <strong>Foto:</strong>
  <%= @membro.foto %>
</p>

<%= link_to 'Edit', edit_membro_path(@membro) %> |
<%= link_to 'Back', membros_path %>