config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/show'

  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"

  get 'ocupacaos/index'
  get "/" => "auth0#login"

  get 'estados' => 'estados#index'
  post 'estados' =>'estados#create'
  post 'groups/cadastrar'

  get 'auth/authenticate'
  get 'sessions/new'
  get 'users/new'

  post 'users/permissions' => 'users#getPermissions'
  post 'login'   => 'users#auntentication'

  resources :tipo_assembleia
  resources :forma_transicaos
  resources :arquivos
  resources :ocupacaos
  resources :assembleia
  resources :forma_ingressos
  resources :pessoas
  resources :igrejas
  resources :configuracaos
  resources :tipo_documentos
  resources :tipo_enderecos
  resources :documentos
  resources :grau_instrucaos
  resources :groups
  resources :profissaos
  resources :situacaos
  resources :users
  resources :acos
  resources :actions
  resources :cidades
  resources :bairros
  resources :membros
  resources :ministerios

  get 'membros/page/:page' => 'membros#index'
  post 'membros/filter' => 'membros#filter'

  post 'congregacao/:id_igreja' => 'igrejas#create_congregacao'
  put 'congregacao/:id_congregacao' => 'igrejas#update_congregacao'

end

app/models/profissao.rb
class Profissao < ActiveRecord::Base
	has_many 	:membros
	belongs_to	:cliente
	
  	validates_presence_of :profissao, message: "Por favor, informe a profissão que deseja cadastra."
end

app/controllers/profissaos_controller.rb
class ProfissaosController < ApplicationController
  before_action :set_profissao, only: [:show, :edit, :update, :destroy]

  # GET /profissaos
  # GET /profissaos.json
  # Description:: Profissões
  def index
    @profissaos = Profissao.all
  end

  # GET /profissaos/1
  # GET /profissaos/1.json
  # Description:: Teste
  def show
  end

  # GET /profissaos/new
  def new
    @profissao = Profissao.new
  end

  # GET /profissaos/1/edit
  def edit
  end

  # POST /profissaos
  # POST /profissaos.json
  def create
    @profissao = Profissao.new(profissao_params)

    respond_to do |format|
      if @profissao.save
        format.html { redirect_to @profissao, notice: 'Profissao was successfully created.' }
        format.json { render :show, status: :created, location: @profissao }
      else
        format.html { render :new }
        format.json { render json: @profissao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profissaos/1
  # PATCH/PUT /profissaos/1.json
  def update
    respond_to do |format|
      if @profissao.update(profissao_params)
        format.html { redirect_to @profissao, notice: 'Profissao was successfully updated.' }
        format.json { render :show, status: :ok, location: @profissao }
      else
        format.html { render :edit }
        format.json { render json: @profissao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profissaos/1
  # DELETE /profissaos/1.json
  def destroy
    @profissao.destroy
    respond_to do |format|
      format.html { redirect_to profissaos_url, notice: 'Profissao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profissao
      @profissao = Profissao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profissao_params
      params.require(:profissao).permit(:profissao)
    end
end

app/views/profissaos/_form.html.erb
<%= form_for(@profissao) do |f| %>
  <% if @profissao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profissao.errors.count, "error") %> prohibited this profissao from being saved:</h2>

      <ul>
      <% @profissao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :profissao %><br>
    <%= f.text_field :profissao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profissaos/edit.html.erb
<h1>Editing Profissao</h1>

<%= render 'form' %>

<%= link_to 'Show', @profissao %> |
<%= link_to 'Back', profissaos_path %>

app/views/profissaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profissaos</h1>

<table>
  <thead>
    <tr>
      <th>Profissao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profissaos.each do |profissao| %>
      <tr>
        <td><%= profissao.profissao %></td>
        <td><%= link_to 'Show', profissao %></td>
        <td><%= link_to 'Edit', edit_profissao_path(profissao) %></td>
        <td><%= link_to 'Destroy', profissao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profissao', new_profissao_path %>

app/views/profissaos/new.html.erb
<h1>New Profissao</h1>

<%= render 'form' %>

<%= link_to 'Back', profissaos_path %>

app/views/profissaos/show.html.erb
<p id="notice"><%= notice %></p>
<%= @headers %>
<p>
  <strong>Profissao:</strong>
  <%= @profissao.profissao %>
</p>

<%= link_to 'Edit', edit_profissao_path(@profissao) %> |
<%= link_to 'Back', profissaos_path %>